launchpad:
  # A list of all materials automatically enabled as a launch-pad. Use +PRESSURE_PLATES for all pressure plates, or 
  # +WOODEN_PRESSURE_PLATES for all wooden pressure plates.
  materials:
    - LIGHT_WEIGHTED_PRESSURE_PLATE # This is the gold pressure plate
    - HEAVY_WEIGHTED_PRESSURE_PLATE # This is the iron pressure plate
  # A whitelist for the materials that can be manually set as a launchpad. If non-empty, only the materials listed can
  # be clicked after executing "/launchpad add" or a different launchpad-editing command. As with materials, this
  # supports tags like +PRESSURE_PLATES
  materialWhitelist: [ ]
  # The default vertical (upwards) velocity for all launchpads
  verticalVelocity: 0.2
  # The default horizontal (outwards) velocity for all launchpads
  horizontalVelocity: 0.5
  # Default velocities for specific launchpad materials. You can use this to set up different velocities for each type
  # of pressure plate or other material.
  materialVelocities:
    LIGHT_WEIGHTED_PRESSURE_PLATE:
      verticalVelocity: 0.2
      horizontalVelocity: 0.5
    HEAVY_WEIGHTED_PRESSURE_PLATE:
      verticalVelocity: 0.3
      horizontalVelocity: 1